### ISSUE TITLE
Resume Error

### ISSUE THREAD

**Issue by jcaruso001** [jcaruso001/MessagePro#3]
1-11 22:28:22.451: E/AndroidRuntime(10888): Process: com.projectcaruso.messagepro, PID: 10888
01-11 22:28:22.451: E/AndroidRuntime(10888): java.lang.IllegalStateException: ImageLoader must be init with configuration before using
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.nostra13.universalimageloader.core.ImageLoader.checkConfiguration(ImageLoader.java:568)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:208)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:303)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.projectcaruso.messagepro.helper.ActiveChatAdapter.loadImage(ActiveChatAdapter.java:109)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.projectcaruso.messagepro.helper.ActiveChatAdapter.getView(ActiveChatAdapter.java:82)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.AbsListView.obtainView(AbsListView.java:2780)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.ListView.makeAndAddView(ListView.java:1811)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.ListView.fillDown(ListView.java:697)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.ListView.fillFromTop(ListView.java:763)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.ListView.layoutChildren(ListView.java:1641)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.AbsListView.onLayout(AbsListView.java:2598)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.View.layout(View.java:15860)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewGroup.layout(ViewGroup.java:4902)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.View.layout(View.java:15860)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewGroup.layout(ViewGroup.java:4902)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.View.layout(View.java:15860)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewGroup.layout(ViewGroup.java:4902)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:461)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.View.layout(View.java:15860)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewGroup.layout(ViewGroup.java:4902)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.View.layout(View.java:15860)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewGroup.layout(ViewGroup.java:4902)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2379)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2092)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1267)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6640)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.Choreographer.doFrame(Choreographer.java:583)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.os.Handler.handleCallback(Handler.java:733)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.os.Looper.loop(Looper.java:146)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at android.app.ActivityThread.main(ActivityThread.java:5635)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
01-11 22:28:22.451: E/AndroidRuntime(10888): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by jcaruso001** [comment]
I believe this issue to be resolved.
